#!/bin/sh

usage() {
cat << EOF
mullvad-wg-custom-dns -s [server name] -a [account number] -d [dns ip] -o [output file]
EOF
}

while getopts s:a:d:o: option
do
    case "${option}"
        in
        s)server=${OPTARG};;
        a)acct_num=${OPTARG};;
        d)dns=${OPTARG};;
        o)file=${OPTARG};;
    esac
done

if [ -z "$server" ] ; then
    usage
    echo "Must provide server name from https://mullvad.net/en/servers/ "
    exit 1
elif [ -z "$acct_num" ]; then
    usage
    echo "Must provide Mullvad Account number"
    exit 1
fi

data=$(curl https://api.mullvad.net/www/relays/wireguard/ 2>/dev/null \
        | sed 's/},{/}\n{/g' | grep $server
      )

if [ -z "$data" ] || [ $(wc -l <<< "$data") -gt 1 ]; then
    echo "Please provide a valid Mullvad Wireguard server hostname"
    exit 1
fi

if grep -q 'active":false' <<< "$data"; then
    echo "Selected server is not currently active"
    exit 1
fi

server_ip=$(echo "$data" | sed 's/.*"ipv4_addr_in":"\(.*\)","ipv6.*/\1/g')
server_pubkey=$(echo "$data" | sed 's/.*"pubkey":"\(.*\)","multihop.*/\1/g')
priv_key=$(wg genkey)
pub_key=$(echo $priv_key | wg pubkey)

response=$(curl -sSL https://api.mullvad.net/app/v1/wireguard-keys \
            -H "Content-Type: application/json" \
            -H "Authorization: Token $acct_num" \
            -d '{"pubkey":"'$pub_key'"}' \
          )

# Check Response for failure
if grep -q "ipv4_address" <<< "$response"; then
    ipv4=$(echo $response | sed 's/.*ipv4_address\":\"\(.*\)\",\"ipv6.*/\1/')
    ipv6=$(echo $response | sed 's/.*ipv6_address\":\"\(.*\)\".*/\1/')
else
    echo "Failure to authenticate with Mullvad API"
    echo "$response"
    exit 1
fi

output="[Interface]
PrivateKey = $priv_key
Address = $ipv4,$ipv6
DNS = $dns

[Peer]
PublicKey = $server_pubkey
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = $server_ip:51820"

if [ -z "$file" ]; then
    echo "$output"
else
    echo "$output" > "$file"
fi
